spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cat?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  mvc:
    servlet:
      load-on-startup: 1
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
access_token:
  store-jwt: false
  jwt-signing-key: xinalng.com=$==+_+%0%:)(:)
  add-userinfo: false
logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
ribbon:
  eager-load:
    enabled: true
    clients: cat-user
  ReadTimeout: 10000
  ConnectTimeout: 10000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
info:
  company: 鑫朗通信技术有限公司
  phone: 18777811286
  email: 516281013@qq.com