logging:
  level:
    root: info
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://local.mysql.com:3306/cat?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  rabbitmq:
    host: localhost
    port: 5672
    username: pig
    password: pig
    virtual-host: /
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false
#    properties:
#      mail.smtp.auth: true
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    sender:
      type: web
mybatis:
  type-aliases-package: com.xinlang.zly_xyx.cat_manage_backend.model,com.xinlang.zly_xyx.email
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true
security:
  oauth2:
    resource:


      user-info-uri: http://192.168.5.64/api-o/user-me

      prefer-token-info: false
info:
  company: 鑫朗通信技术有限公司
  phone: 18777811286
  email: 516281013@qq.com