#开发环境配置
server:
  port: 8761

spring:
  security:
    user:
      name: cat
      password: cat
      roles: SUPERUSER
  application:
    name: cat-eureka

eureka:
  instance:
    hostname: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
<<<<<<< HEAD
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@192.168.5.13:${server.port}/eureka/
=======
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@192.168.5.13:${server.port}/eureka/
>>>>>>> 367a780c16bcb6778ff608edc48294f373d6df37
    registry-fetch-interval-seconds: 5
  server:
    eviction-interval-timer-in-ms: 3000
    enable-self-preservation: false
    renewal-percent-threshold: 0.9

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info
  file: logs/${spring.application.name}.log

info:
  company: 鑫朗通信技术有限公司
  phone: 18777811286
  email: 516281013@qq.com
