/*
Navicat MySQL Data Transfer

Source Server         : MySQL
Source Server Version : 50728
Source Host           : localhost:3306
Source Database       : cat

Target Server Type    : MYSQL
Target Server Version : 50728
File Encoding         : 65001

Date: 2020-03-19 15:27:00
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for project_check_table
-- ----------------------------
DROP TABLE IF EXISTS `project_check_table`;
CREATE TABLE `project_check_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `create_user_id` int(11) DEFAULT NULL COMMENT '创建人id',
  `item_id` int(11) DEFAULT NULL COMMENT '项目id',
  `application_date` datetime DEFAULT NULL COMMENT '申请日期',
  `suggest_date` datetime DEFAULT NULL COMMENT '申请验收单位建议的验收日期',
  `cean` longtext COMMENT '项目合同（或课件任务书）约定的目标任务与技术经济指标完成情况',
  `katalog` longtext COMMENT '提交的验收文件和资料目录',
  `application_dept_opinion` longtext COMMENT ' 申请验收单位意见',
  `manage_dept_opinion` longtext COMMENT '受委托管理单位或项目牵头承担单位意见',
  `burg_leader_opinion` longtext COMMENT '自治区科技同项目',
  `burg_finance_opinion` longtext COMMENT '自治区科技厅条件财务处意见',
  `THE_IMPORTED_TECHNOLOGY` int(11) DEFAULT NULL,
  `INTEGRATED_APPLICATION_TECHNOLOGY` int(11) DEFAULT NULL,
  `NEW_INDUSTRIAL_PRODUCT` int(11) DEFAULT NULL,
  `NEW_AGRICULTURAL_VARIETY` int(11) DEFAULT NULL,
  `THE_NEW_TECHNOLOGY` int(11) DEFAULT NULL,
  `THE_NEW_MATERIAL` int(11) DEFAULT NULL,
  `THE_NEW_DEVICE` int(11) DEFAULT NULL,
  `REGISTER_COMPUTER_SOFTWARE` int(11) DEFAULT NULL,
  `RESEARCH_AND_DEVELOPMENT_PLATFORM` int(11) DEFAULT NULL,
  `SCIENCE_INFORMATION_PLATFORM` int(11) DEFAULT NULL,
  `PILOT_STUDIES` int(11) DEFAULT NULL,
  `PILOT_LINE` int(11) DEFAULT NULL,
  `THE_PRODUCTION_LINE` int(11) DEFAULT NULL,
  `EXPERIMENTAL_BASE` int(11) DEFAULT NULL,
  `APPLICATION_FOR_PATENT` int(11) DEFAULT NULL,
  `APPLICATION_FOR_INVENTION_PATENT` int(11) DEFAULT NULL,
  `APPLICATION_FOR_UTILITY_PATEN` int(11) DEFAULT NULL,
  `AUTHORIZED_PATENT` int(11) DEFAULT NULL,
  `AUTHORIZED_INVENTION_PATENT` int(11) DEFAULT NULL,
  `AUTHORIZED_UTILITY_PATENT` int(11) DEFAULT NULL,
  `COUNT_STANDARD` int(11) DEFAULT NULL,
  `THE_NATIONAL_STANDARD` int(11) DEFAULT NULL,
  `THE_INTERNATIONAL_STANDARD` int(11) DEFAULT NULL,
  `THE_INDUSTRY_STANDARD` int(11) DEFAULT NULL,
  `LOCAL_STANDARD` int(11) DEFAULT NULL,
  `THE_ENTERPRISE_STANDARD` int(11) DEFAULT NULL,
  `COUNT_THESIS` int(11) DEFAULT NULL,
  `DOMESTIC_PAPERS` int(11) DEFAULT NULL,
  `FOREIGN_PAPERS` int(11) DEFAULT NULL,
  `MAKE_POSTDOCTOR` int(11) DEFAULT NULL,
  `MAKE_DOCTOR` int(11) DEFAULT NULL,
  `MAKE_POSTGRADUATE` int(11) DEFAULT NULL,
  `HOLD_TRAINING_COURSES` int(11) DEFAULT NULL,
  `NUMBER_OF_PARTICIPANTS` int(11) DEFAULT NULL,
  `CONVERT_THE_NUMBER_OF_APPLICATIONS` int(11) DEFAULT NULL,
  `RESULTS_OF_INDUSTRIALIZATION` int(11) DEFAULT NULL,
  `ACHIEVEMENT_TRANSFER_CONTRACT` int(11) DEFAULT NULL,
  `TOTAL_AMOUNT_OF_ACHIEVEMENT_TRANSFER_CONTRACT` float(6,0) DEFAULT NULL,
  `ALL_PRODUCTION_A` float(6,0) DEFAULT NULL,
  `THE_NEW_PRODUCTION_A` float(6,0) DEFAULT NULL,
  `THE_NEW_TAX_A` float(6,0) DEFAULT NULL,
  `NET_AMOUNT_A` float(6,0) DEFAULT NULL,
  `ALL_PRODUCTION_B` float(6,0) DEFAULT NULL,
  `THE_NEW_PRODUCTION_B` float(6,0) DEFAULT NULL,
  `THE_NEW_TAX_B` float(6,0) DEFAULT NULL,
  `NET_AMOUNT_B` float(6,0) DEFAULT NULL,
  `ALL_PRODUCTION_YEAR` float(6,0) DEFAULT NULL,
  `THE_NEW_PRODUCTION_YEAR` float(6,0) DEFAULT NULL,
  `THE_NEW_TAX_YEAR` float(6,0) DEFAULT NULL,
  `NET_AMOUNT_YEAR` float(6,0) DEFAULT NULL,
  `the_company_number` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC;
